### ISSUE TITLE
Major workflow refactor TODO

### ISSUE THREAD

**Issue by Picalines** [Picalines/outer-scout#1]
- [x] Merge BodyMeshExporter mod

General workflow should be:
- [x] Load ground body in Blender
- [x] Edit camera & hdri movement there, send it to Outer Wilds
- [ ] Test movement in game
- [x] Render footage in game, save it near the Blender project
- [x] Render buttons should be in special panel in Blebder
- [x] Allow changing stuff in such project

...

PROFIT!!!
